//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foghorn.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.Priority = 0;
            this.Sticky = false;
            this.SentToSubscribers = new HashSet<Subscriber>();
        }
    
        public int NotificationId { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationMessage { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public int Priority { get; set; }
        public bool Sticky { get; set; }
    
        public virtual ICollection<Subscriber> SentToSubscribers { get; set; }
        public virtual NotificationType NotificationType { get; set; }
    }
}
