//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foghorn.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendingApplication
    {
        public SendingApplication()
        {
            this.Subscribers = new HashSet<Subscriber>();
            this.NotificationTypes = new HashSet<NotificationType>();
        }
    
        public int SendingApplicationId { get; set; }
        public string SendingApplicationName { get; set; }
        public byte[] SendingApplicationIcon { get; set; }
    
        public virtual ICollection<Subscriber> Subscribers { get; set; }
        public virtual ICollection<NotificationType> NotificationTypes { get; set; }
    }
}
