//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foghorn.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public Subscriber()
        {
            this.NotificationsSent = new HashSet<Notification>();
        }
    
        public System.Guid SubscriberId { get; set; }
        public string SubscriberName { get; set; }
        public Nullable<int> Port { get; set; }
        public string HostName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Notification> NotificationsSent { get; set; }
        public virtual SendingApplication SendingApplication { get; set; }
    }
}
